#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias git="noglob hub"
# compdef hub=git

. <(npm completion)

export PYTHONPATH=/usr/local/lib/python2.7/site-packages/
eval "$(rbenv init -)"

function wmake() {
	deps=$(make -nBd $@ | grep 'No need' | cut -d '`' -f 2 | cut -d "'" -f 1)
	echo Watching: $(echo $deps | tr "\n" " ")
	make $@
	fswatch-run $deps "make $@"
}

export NODE_REPL_HISTORY_FILE=~/.node_history
